KaieteurJungle_Route11_MapScripts::
	.byte 0


KaieteurJungle_Route11_Sign::
# 5 "data/maps/KaieteurJungle_Route11/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route11/scripts.pory"
	msgbox KaieteurJungle_Route11_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route11/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route11/scripts.pory"
	release
	end


KaieteurJungle_Route11_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route11/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 11\p"
	.string "Leaving TOPSOIL TOWN.$"
