TopsoilTown_MapScripts::
	.byte 0


TopsoilTown_Sign::
# 5 "data/maps/TopsoilTown/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown/scripts.pory"
	msgbox TopsoilTown_Sign_Text_0
# 7 "data/maps/TopsoilTown/scripts.pory"
	closemessage
# 8 "data/maps/TopsoilTown/scripts.pory"
	release
	end


TopsoilTown_Sign_Text_0:
# 6 "data/maps/TopsoilTown/scripts.pory"
	.string "TOPTOIL TOWN -\n"
	.string "GUYANA'S hidden agricultural haven.$"
