AzaleaTown_IlexForest_Entrance_MapScripts::
	.byte 0


AzaleaTown_IlexForest_Entrance_Guard::
# 5 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	lock
# 6 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	faceplayer
# 7 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	msgbox AzaleaTown_IlexForest_Entrance_Guard_Text_0
# 8 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	closemessage
# 9 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	release
	end


AzaleaTown_IlexForest_Entrance_Guard_Text_0:
# 7 "data/maps/AzaleaTown_IlexForest_Entrance/scripts.pory"
	.string "ILEX FOREST is up ahead.\n"
	.string "Be careful not to get lost.$"
