GoldenrodCity_GTS_2F_MapScripts::
	.byte 0


GoldenrodCity_GTS_2F_Little_Boy::
# 5 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	lock
# 6 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	faceplayer
# 7 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	msgbox GoldenrodCity_GTS_2F_Little_Boy_Text_0
# 8 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	closemessage
# 9 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	release
	end


GoldenrodCity_GTS_2F_Little_Boy_Text_0:
# 7 "data/maps/GoldenrodCity_GTS_2F/scripts.pory"
	.string "There are some weird people\n"
	.string "in the computer room here.\p"
	.string "I thought they would be easy\n"
	.string "to kick out, but no!\p"
	.string "They're honestly no joke...$"
