Route5_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

Route5_Text_ProfOakAideSwitchBattleMode::
    .string "Hi {PLAYER}!\p"
    .string "I’m one of PROF. OAK's\n"
    .string "countless aides.\n"
    .string "Would you like to enable\p"
    .string "GO Wild Mode?$"

Route5_Text_ProfOakAideConfirmation::
    .string "Got it! Please keep in mind\p"
    .string "that entering a trainer battle\n"
    .string "or Safari Zone will reset the\p"
    .string "GO Wild Battle mode.$"
