BlackthornCity_House2_MapScripts::
	.byte 0


BlackthornCity_House2_Old_Woman::
# 5 "data/maps/BlackthornCity_House2/scripts.pory"
	lock
# 6 "data/maps/BlackthornCity_House2/scripts.pory"
	faceplayer
# 7 "data/maps/BlackthornCity_House2/scripts.pory"
	msgbox BlackthornCity_House2_Old_Woman_Text_0
# 8 "data/maps/BlackthornCity_House2/scripts.pory"
	closemessage
# 9 "data/maps/BlackthornCity_House2/scripts.pory"
	release
	end


BlackthornCity_House2_Old_Woman_Text_0:
# 7 "data/maps/BlackthornCity_House2/scripts.pory"
	.string "LORELEI and CLAIR prefer to\n"
	.string "keep their distance.\p"
	.string "Those two don't get along\n"
	.string "very well with each other.$"
