LindenTown_House10_MapScripts::
	.byte 0


LindenTown_House10_Cooltrainer_M::
# 5 "data/maps/LindenTown_House10/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House10/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House10/scripts.pory"
	msgbox LindenTown_House10_Cooltrainer_M_Text_0
# 8 "data/maps/LindenTown_House10/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House10/scripts.pory"
	release
	end


LindenTown_House10_Cooltrainer_M_Text_0:
# 7 "data/maps/LindenTown_House10/scripts.pory"
	.string "You have POKéMON, huh?\n"
	.string "Lucky...$"
