Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about SEISMIC TOSS?\n"
    .string "Should I teach that to a POKéMON?$"

Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, huh?\p"
    .string "What's so special about it?\n"
    .string "Looks like an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "Ah, I still remember that!\n"
    .string "It was SUNDAY, JULY 20, 1969...\p"
    .string "APOLLO 11 first set foot on\n"
    .string "the moon that day.\p"
    .string "I bought a color TV just so I\n"
    .string "could watch that news.\p"
    .string "That's one small step for man,\n"
    .string "one giant leap for mankind!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "This month, we have a new space\n"
    .string "exhibit up and running.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "I want a PIKACHU!\n"
    .string "It's so cute!\p"
    .string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Yeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "NASA SPACE SHUTTLE ORBITER\n"
    .string "COLUMBIA (OV-102) REPLICA\p"
    .string "The very first space orbiter,\n"
    .string "still circling our WORLD.\p"
    .string "It first launched on SUNDAY,\n"
    .string "APRIL 12, 1981!\p"
    .string "To this day, it endures many\n"
    .string "long-lasting science missions.$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "A meteorite that fell on MT. MOON.\n"
    .string "It is thought to be a MOON STONE.$"

