LindenTown_House8_MapScripts::
	.byte 0


LindenTown_House8_Little_Boy::
# 5 "data/maps/LindenTown_House8/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House8/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House8/scripts.pory"
	msgbox LindenTown_House8_Little_Boy_Text_0
# 8 "data/maps/LindenTown_House8/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House8/scripts.pory"
	release
	end


LindenTown_House8_Youngster::
# 15 "data/maps/LindenTown_House8/scripts.pory"
	lock
# 16 "data/maps/LindenTown_House8/scripts.pory"
	faceplayer
# 17 "data/maps/LindenTown_House8/scripts.pory"
	msgbox LindenTown_House8_Youngster_Text_0
# 18 "data/maps/LindenTown_House8/scripts.pory"
	closemessage
# 19 "data/maps/LindenTown_House8/scripts.pory"
	release
	end


LindenTown_House8_Little_Boy_Text_0:
# 7 "data/maps/LindenTown_House8/scripts.pory"
	.string "Hey, I'm trying to gather\n"
	.string "enough players for a campaign!\p"
	.string "Spread the word!$"

LindenTown_House8_Youngster_Text_0:
# 17 "data/maps/LindenTown_House8/scripts.pory"
	.string "My little brother is trying\n"
	.string "to play a board game.\p"
	.string "I don't get it!$"
