EcruteakCity_BarrierStation_MapScripts::
	.byte 0


EcruteakCity_BarrierStation_OldMan_Placeholder::
# 5 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	lock
# 6 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	faceplayer
# 7 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	msgbox EcruteakCity_BarrierStation_OldMan_Placeholder_Text_0
# 8 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	msgbox EcruteakCity_BarrierStation_OldMan_Placeholder_Text_1
# 9 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	msgbox EcruteakCity_BarrierStation_OldMan_Placeholder_Text_2
# 10 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	closemessage
# 11 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	release
	end


EcruteakCity_BarrierStation_OldMan_Placeholder_Text_0:
# 7 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	.string "Hm?\n"
	.string "Are you with maintenance?\p"
	.string "Thank goodness! My apartment's\n"
	.string "plumbing broke again, and...$"

EcruteakCity_BarrierStation_OldMan_Placeholder_Text_1:
# 8 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	.string "Oh, wait, you aren't...\n"
	.string "You're not even MR. HAN'S...\p"
	.string "Never mind...\n"
	.string "Oh, but do you like this song?$"

EcruteakCity_BarrierStation_OldMan_Placeholder_Text_2:
# 9 "data/maps/EcruteakCity_BarrierStation/scripts.pory"
	.string "CALYPSO from the DEV CLUB in\n"
	.string "GOLDENROD CITY made this for me!$"
