SevenIsland_TanobyRuins_MapScripts::
	.byte 0


SevenIsland_TanobyRuins_Janitor::
# 8 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	lock
# 9 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	faceplayer
# 10 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	msgbox SevenIsland_TanobyRuins_Janitor_Text_0
# 11 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	closemessage
# 12 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	release
	end


SevenIsland_TanobyRuins_Janitor_Text_0:
# 10 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "I'm a JANITOR here, picking up\n"
	.string "litter near the seashore.\p"
	.string "You can help me, by not\n"
	.string "littering, kindly.$"
