VioletCity_House1_MapScripts::
	.byte 0


VioletCity_House1_BaldingMan::
# 5 "data/maps/VioletCity_House1/scripts.pory"
	lock
# 6 "data/maps/VioletCity_House1/scripts.pory"
	faceplayer
# 7 "data/maps/VioletCity_House1/scripts.pory"
	msgbox VioletCity_House1_BaldingMan_Text_0
# 8 "data/maps/VioletCity_House1/scripts.pory"
	closemessage
# 9 "data/maps/VioletCity_House1/scripts.pory"
	release
	end


VioletCity_House1_BaldingMan_Text_0:
# 7 "data/maps/VioletCity_House1/scripts.pory"
	.string "The mysterious RUINS OF ALPH\n"
	.string "seem to predate early JOHTO...\p"
	.string "I'm talking at least 1,000 year-\n"
	.string "old ruins! Hm...$"
