TopsoilTown_MasterHouse_MapScripts::
	.byte 0


TopsoilTown_MasterHouse_BerryMaster::
# 5 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	faceplayer
# 7 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	msgbox TopsoilTown_MasterHouse_BerryMaster_Text_0
# 8 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	closemessage
# 9 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	release
	end


TopsoilTown_MasterHouse_BerryMaster_Text_0:
# 7 "data/maps/TopsoilTown_MasterHouse/scripts.pory"
	.string "I am the BERRY MASTER.\n"
	.string "You're visiting from KANTO?\p"
	.string "Hm, that is very far.\n"
	.string "Very far away, yes...$"
