#ifndef GUARD_CONSTANTS_SPECIES_EXPANDED_1_H
#define GUARD_CONSTANTS_SPECIES_EXPANDED_1_H

//These "species" correspond with u8 species_form_id:4 having a value of '1', essentially another form of existing species.

#define SPECIES_NONE_1 0 //SPECIES_NONE
#define SPECIES_TURTWIG 1 //SPECIES_BULBASAUR
#define SPECIES_GROTLE 2 //SPECIES_IVYSAUR
#define SPECIES_TORTERRA 3 //SPECIES_VENUSAUR

#define SPECIES_EGG_EXPANDED_1 412 // Limit

#define NUM_SPECIES_EXPANDED_1 SPECIES_EGG_EXPANDED_1

#endif  // GUARD_CONSTANTS_SPECIES_EXPANDED_1_H