BlackthornCity_House1_MapScripts::
	.byte 0


BlackthornCity_House1_Lass::
# 5 "data/maps/BlackthornCity_House1/scripts.pory"
	lock
# 6 "data/maps/BlackthornCity_House1/scripts.pory"
	faceplayer
# 7 "data/maps/BlackthornCity_House1/scripts.pory"
	msgbox BlackthornCity_House1_Lass_Text_0
# 8 "data/maps/BlackthornCity_House1/scripts.pory"
	closemessage
# 9 "data/maps/BlackthornCity_House1/scripts.pory"
	release
	end


BlackthornCity_House1_Lass_Text_0:
# 7 "data/maps/BlackthornCity_House1/scripts.pory"
	.string "That's quite an impressive set\n"
	.string "of BADGES you have there.$"
