CanalaveCity_Gym_3F_MapScripts::
	.byte 0


CanalaveCity_Gym_3F_Hiker_Jackson_Battle::
# 5 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_JACKSON, CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_0, CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_1
# 6 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	msgbox CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_2
# 7 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	release
	end


CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle::
# 13 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	trainerbattle_single TRAINER_COOLTRAINER_CESAR, CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_0, CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_1
# 14 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	msgbox CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_2
# 15 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	release
	end


CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_0:
# 5 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "I just love being up high!$"

CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_1:
# 5 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "This place leaves me speechless!$"

CanalaveCity_Gym_3F_Hiker_Jackson_Battle_Text_2:
# 6 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "Getting lost yet?$"

CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_0:
# 13 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "Yo, I'm feeling ready!\n"
	.string "Yeah, I'm so ready!\p"
	.string "Come on!$"

CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_1:
# 13 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "Dude... Not cool!$"

CanalaveCity_Gym_3F_CoolTrainer_Cesar_Battle_Text_2:
# 14 "data/maps/CanalaveCity_Gym_3F/scripts.pory"
	.string "You totally ruined my vibe!\n"
	.string "But your vibe is going strong!$"
