ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Hey, did you hear the news?\n"
    .string "We've discovered more POKéMON!\p"
    .string "I wonder how many there are?\n"
    .string "There are still so many to find!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "It's impossible to SURF between the\n"
    .string "islands around these parts.\p"
    .string "The tides are too fast and\n"
    .string "treacherous.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Let's crush BERRIES!\n"
    .string "…That'd be wasting BERRIES?\p"
    .string "You can always find some BERRIES\n"
    .string "on the ground in BERRY FOREST.$"

