Text_WantToRockClimb::
	.string "The cliff looks possible to scale!\n"
	.string "Would you like to ROCK CLIMB?$"

Text_UsedRockClimb::
	.string "{PLAYER} used the\n"
	.string "EXPLORER KIT!$"

Text_CantUseRockClimb::
	.string "It's a rocky cliff ledge...$"

Text_WantToDigDown::
	.string "Want to dig a hole and\n"
	.string "go UNDERGROUND?$"

Text_WantToEscapeUp::
	.string "Want to climb back up\n"
	.string "instead?$"

Text_UsedExplorerKitUp::
	.string "{PLAYER} used the\n"
	.string "EXPLORER KIT!$"

Text_UsedExplorerKitDown::
	.string "{PLAYER} used the\n"
	.string "EXPLORER KIT!$"

Text_UsedExplorerKitButNothingHappened::
	.string "...But nothing interesting\n"
	.string "happened.$"
