Route41_MapScripts::
	.byte 0


Route41_EventScript_Whirlpool::
# 5 "data/maps/Route41/scripts.pory"
	msgbox Route41_EventScript_Whirlpool_Text_0
# 6 "data/maps/Route41/scripts.pory"
	closemessage
# 7 "data/maps/Route41/scripts.pory"
	release
	end


Route41_EventScript_Whirlpool_Text_0:
# 5 "data/maps/Route41/scripts.pory"
	.string "A violent whirlpool is in the way!\n"
	.string "It looks like it could be calmed...$"
