KaieteurJungle_Route3_MapScripts::
	.byte 0


KaieteurJungle_Route3_ExplorersMemo_Sign::
# 5 "data/maps/KaieteurJungle_Route3/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route3/scripts.pory"
	msgbox KaieteurJungle_Route3_ExplorersMemo_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route3/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route3/scripts.pory"
	release
	end


KaieteurJungle_Route3_Sign::
# 14 "data/maps/KaieteurJungle_Route3/scripts.pory"
	lock
# 15 "data/maps/KaieteurJungle_Route3/scripts.pory"
	msgbox KaieteurJungle_Route3_Sign_Text_0
# 16 "data/maps/KaieteurJungle_Route3/scripts.pory"
	closemessage
# 17 "data/maps/KaieteurJungle_Route3/scripts.pory"
	release
	end


KaieteurJungle_Route3_ExplorersMemo_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route3/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 3$"

KaieteurJungle_Route3_Sign_Text_0:
# 15 "data/maps/KaieteurJungle_Route3/scripts.pory"
	.string "It's an explorer's note, dated:\n"
	.string "June 28th, 1995.\p"
	.string "In embrace of the jungle's\n"
	.string "dense growth, explorers beware...\p"
	.string "For just as the flowers find\n"
	.string "its path to light...\p"
	.string "We, too, can discover the\n"
	.string "profound compass within it.$"
