MahoganyTown_MapScripts::
	.byte 0


MahoganyTown_Sign::
# 5 "data/maps/MahoganyTown/scripts.pory"
	lock
# 6 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Sign_Text_0
# 7 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 8 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_JustASouvenirShop_Sign::
# 14 "data/maps/MahoganyTown/scripts.pory"
	lock
# 15 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_JustASouvenirShop_Sign_Text_0
# 16 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 17 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_Gym_Sign::
# 23 "data/maps/MahoganyTown/scripts.pory"
	lock
# 24 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Gym_Sign_Text_0
# 25 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 26 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_Woman_1::
# 32 "data/maps/MahoganyTown/scripts.pory"
	lock
# 33 "data/maps/MahoganyTown/scripts.pory"
	faceplayer
# 34 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Woman_1_Text_0
# 35 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 36 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_OldMan_1::
# 42 "data/maps/MahoganyTown/scripts.pory"
	lock
# 43 "data/maps/MahoganyTown/scripts.pory"
	faceplayer
# 44 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_OldMan_1_Text_0
# 45 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 46 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_Youngster::
# 52 "data/maps/MahoganyTown/scripts.pory"
	lock
# 53 "data/maps/MahoganyTown/scripts.pory"
	faceplayer
# 54 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Youngster_Text_0
# 55 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Youngster_Text_1
# 56 "data/maps/MahoganyTown/scripts.pory"
	closemessage
# 57 "data/maps/MahoganyTown/scripts.pory"
	release
	end


MahoganyTown_Sign_Text_0:
# 6 "data/maps/MahoganyTown/scripts.pory"
	.string "MAHOGANY TOWN -\n"
	.string "Welcome to the Home of the Ninja!$"

MahoganyTown_JustASouvenirShop_Sign_Text_0:
# 15 "data/maps/MahoganyTown/scripts.pory"
	.string "JUST A SOUVENIR SHOP\n"
	.string "We sell unique, high-value items!\p"
	.string "Nothing suspicious about this...\n"
	.string "Really, no need to be alarmed...$"

MahoganyTown_Gym_Sign_Text_0:
# 24 "data/maps/MahoganyTown/scripts.pory"
	.string "MAHOGANY TOWN POKéMON GYM\n"
	.string "LEADER: PRYCE\p"
	.string "A mentor on the winter harshness!$"

MahoganyTown_Woman_1_Text_0:
# 34 "data/maps/MahoganyTown/scripts.pory"
	.string "Have you been to the\n"
	.string "SOUVENIR SHOP yet? It's right here!\p"
	.string "If you're visiting, you should see\n"
	.string "what's on sale!$"

MahoganyTown_OldMan_1_Text_0:
# 44 "data/maps/MahoganyTown/scripts.pory"
	.string "PRYCE may be as old as me, but he\n"
	.string "has ages of knowledge.\p"
	.string "His long life hardened him into the\n"
	.string "WINTER TRAINER he is now.$"

MahoganyTown_Youngster_Text_0:
# 54 "data/maps/MahoganyTown/scripts.pory"
	.string "Nothing ever happens in this boring\n"
	.string "place... The Ninjas were so cool!\p"
	.string "We need some sort of high-stakes\n"
	.string "action here against evil...$"

MahoganyTown_Youngster_Text_1:
# 55 "data/maps/MahoganyTown/scripts.pory"
	.string "That would just be decent, right?\n"
	.string "I'm so bored here!$"
