MtMoon_Square_Shop_MapScripts::
	.byte 0


MtMoon_Square_Shop_Old_Man::
# 5 "data/maps/MtMoon_Square_Shop/scripts.pory"
	lock
# 6 "data/maps/MtMoon_Square_Shop/scripts.pory"
	msgbox MtMoon_Square_Shop_Old_Man_Text_0
# 7 "data/maps/MtMoon_Square_Shop/scripts.pory"
	waitmessage
# 8 "data/maps/MtMoon_Square_Shop/scripts.pory"
	closemessage
# 9 "data/maps/MtMoon_Square_Shop/scripts.pory"
	releaseall
	end


MtMoon_Square_Shop_Old_Man_Text_0:
# 6 "data/maps/MtMoon_Square_Shop/scripts.pory"
	.string "Hello... You came here to\n"
	.string "see the CLEFAIRY dance?\p"
	.string "Outside, there is a big crater,\n"
	.string "which is hard to miss.\p"
	.string "But they only dance at night.\n"
	.string "Hmm...\p"
	.string "Come to think of it, when was\n"
	.string "the last time I saw sunset?$"
