GoldenrodCity_FortuneTeller_MapScripts::
	.byte 0


GoldenrodCity_FortuneTeller_Felicity::
# 5 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	lock
# 6 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	faceplayer
# 7 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	msgbox GoldenrodCity_FortuneTeller_Felicity_Text_0
# 8 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	closemessage
# 9 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	release
	end


GoldenrodCity_FortuneTeller_Felicity_Text_0:
# 7 "data/maps/GoldenrodCity_FortuneTeller/scripts.pory"
	.string "You've found what was sought!\n"
	.string "Welcome to FELICITY'S FORTUNE TENT.$"
