KaieteurJungle_Route6_MapScripts::
	.byte 0


KaieteurJungle_Route6_Sign::
# 5 "data/maps/KaieteurJungle_Route6/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route6/scripts.pory"
	msgbox KaieteurJungle_Route6_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route6/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route6/scripts.pory"
	release
	end


KaieteurJungle_Route6_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route6/scripts.pory"
	.string "It's a notice from DR. FUJI,\n"
	.string "dated: September 6th, 1996.\p"
	.string "If any human sets foot\n"
	.string "here, again...\p"
	.string "Let it be a kind-hearted person.\p"
	.string "With that hope, I depart\n"
	.string "from GUYANA...$"
