SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Welcome, {PLAYER}!\p"
    .string "Looking for the PRESIDENT?\n"
    .string "Of course!\p"
    .string "The PRESIDENT'S in his suite on\n"
    .string "11F, as usual.\p"
    .string "The elevator should get you there\n"
    .string "a bit faster...\p"
    .string "Thank you so much for saving us.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

