LindenTown_House1_MapScripts::
	.byte 0


LindenTown_House1_Boy::
# 5 "data/maps/LindenTown_House1/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House1/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House1/scripts.pory"
	msgbox LindenTown_House1_Boy_Text_0
# 8 "data/maps/LindenTown_House1/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House1/scripts.pory"
	release
	end


LindenTown_House1_Boy_Text_0:
# 7 "data/maps/LindenTown_House1/scripts.pory"
	.string "Hello...\n"
	.string "Can I help you?\p"
	.string "...Do you normally barge into\n"
	.string "peoples' houses, uninvited?$"
