KaieteurJungle_Route1_MapScripts::
	.byte 0


KaieteurJungle_Route1_Sign::
# 5 "data/maps/KaieteurJungle_Route1/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route1/scripts.pory"
	msgbox KaieteurJungle_Route1_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route1/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route1/scripts.pory"
	release
	end


KaieteurJungle_Route1_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route1/scripts.pory"
	.string "KAIETEUR JUNGLE - ROUTE 1\n"
	.string "Path to LINDEN TOWN ahead!$"
