TopsoilTown_House1_MapScripts::
	.byte 0


TopsoilTown_House1_Balding_Man::
# 5 "data/maps/TopsoilTown_House1/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown_House1/scripts.pory"
	faceplayer
# 7 "data/maps/TopsoilTown_House1/scripts.pory"
	msgbox TopsoilTown_House1_Balding_Man_Text_0
# 8 "data/maps/TopsoilTown_House1/scripts.pory"
	closemessage
# 9 "data/maps/TopsoilTown_House1/scripts.pory"
	release
	end


TopsoilTown_House1_Balding_Man_Text_0:
# 7 "data/maps/TopsoilTown_House1/scripts.pory"
	.string "Another day, another berry...\n"
	.string "I've worked here my whole life.$"
