LindenTown_House2_MapScripts::
	.byte 0


LindenTown_House2_Balding_Man::
# 5 "data/maps/LindenTown_House2/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House2/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House2/scripts.pory"
	msgbox LindenTown_House2_Balding_Man_Text_0
# 8 "data/maps/LindenTown_House2/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House2/scripts.pory"
	release
	end


LindenTown_House2_Tuber_F::
# 15 "data/maps/LindenTown_House2/scripts.pory"
	lock
# 16 "data/maps/LindenTown_House2/scripts.pory"
	faceplayer
# 17 "data/maps/LindenTown_House2/scripts.pory"
	msgbox LindenTown_House2_Tuber_F_Text_0
# 18 "data/maps/LindenTown_House2/scripts.pory"
	closemessage
# 19 "data/maps/LindenTown_House2/scripts.pory"
	release
	end


LindenTown_House2_Balding_Man_Text_0:
# 7 "data/maps/LindenTown_House2/scripts.pory"
	.string "I was being strategic when\n"
	.string "I purchased this house.\p"
	.string "We're right next to a\n"
	.string "POKéMON CENTER, so, the value rises.$"

LindenTown_House2_Tuber_F_Text_0:
# 17 "data/maps/LindenTown_House2/scripts.pory"
	.string "My daddy is so smart!\n"
	.string "I wonder where he got it from?$"
