IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the POKéMON LEAGUE, you will\n"
    .string "face the ELITE FOUR all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "From here on, you face the\n"
    .string "ELITE FOUR one by one.\p"
    .string "If you win, a door opens to the\n"
    .string "next TRAINER. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "LORELEI of the ELITE FOUR is\n"
    .string "absent, you see.\p"
    .string "As a result, the POKéMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "From what I've heard, her RIVAL'S\n"
    .string "accomplishments led to her choices.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member runs in the family.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's also a GYM LEADER.\p"
    .string "Far away? No, not really...$"
