KaieteurJungle_Route5_MapScripts::
	.byte 0


KaieteurJungle_Route5_Sign::
# 5 "data/maps/KaieteurJungle_Route5/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route5/scripts.pory"
	msgbox KaieteurJungle_Route5_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route5/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route5/scripts.pory"
	release
	end


KaieteurJungle_Route5_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route5/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 5 - MT. MORA FOOTHILLS$"
