KaieteurJungle_Route12_MapScripts::
	.byte 0


KaieteurJungle_Route12_Sign::
# 5 "data/maps/KaieteurJungle_Route12/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route12/scripts.pory"
	msgbox KaieteurJungle_Route12_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route12/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route12/scripts.pory"
	release
	end


KaieteurJungle_Route12_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route12/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 12$"
