LindenTown_House6_MapScripts::
	.byte 0


LindenTown_House6_Worker_F::
# 5 "data/maps/LindenTown_House6/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House6/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House6/scripts.pory"
	msgbox LindenTown_House6_Worker_F_Text_0
# 8 "data/maps/LindenTown_House6/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House6/scripts.pory"
	release
	end


LindenTown_House6_Woman_2::
# 15 "data/maps/LindenTown_House6/scripts.pory"
	lock
# 16 "data/maps/LindenTown_House6/scripts.pory"
	faceplayer
# 17 "data/maps/LindenTown_House6/scripts.pory"
	msgbox LindenTown_House6_Woman_2_Text_0
# 18 "data/maps/LindenTown_House6/scripts.pory"
	closemessage
# 19 "data/maps/LindenTown_House6/scripts.pory"
	release
	end


LindenTown_House6_Worker_F_Text_0:
# 7 "data/maps/LindenTown_House6/scripts.pory"
	.string "There are definitely better\n"
	.string "places to live in our world.$"

LindenTown_House6_Woman_2_Text_0:
# 17 "data/maps/LindenTown_House6/scripts.pory"
	.string "It's hard to imagine what\n"
	.string "it'd be like living elsewhere.$"
