BlackthornCity_MapScripts::
	.byte 0


BlackthornCity_Sign::
# 5 "data/maps/BlackthornCity/scripts.pory"
	lock
# 6 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Sign_Text_0
# 7 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 8 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Gym_Sign::
# 14 "data/maps/BlackthornCity/scripts.pory"
	lock
# 15 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Gym_Sign_Text_0
# 16 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 17 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Ice_Path_Ahead_Sign::
# 23 "data/maps/BlackthornCity/scripts.pory"
	lock
# 24 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Ice_Path_Ahead_Sign_Text_0
# 25 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 26 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Move_Specialists_House_Sign::
# 32 "data/maps/BlackthornCity/scripts.pory"
	lock
# 33 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Move_Specialists_House_Sign_Text_0
# 34 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 35 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_TrainerTips_Sign::
# 41 "data/maps/BlackthornCity/scripts.pory"
	lock
# 42 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_TrainerTips_Sign_Text_0
# 43 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 44 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Battle_Girl::
# 50 "data/maps/BlackthornCity/scripts.pory"
	lock
# 51 "data/maps/BlackthornCity/scripts.pory"
	faceplayer
# 52 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Battle_Girl_Text_0
# 53 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 54 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Old_Man::
# 60 "data/maps/BlackthornCity/scripts.pory"
	lock
# 61 "data/maps/BlackthornCity/scripts.pory"
	faceplayer
# 62 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Old_Man_Text_0
# 63 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 64 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Old_Woman::
# 70 "data/maps/BlackthornCity/scripts.pory"
	lock
# 71 "data/maps/BlackthornCity/scripts.pory"
	faceplayer
# 72 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Old_Woman_Text_0
# 73 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 74 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Man::
# 80 "data/maps/BlackthornCity/scripts.pory"
	lock
# 81 "data/maps/BlackthornCity/scripts.pory"
	faceplayer
# 82 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Man_Text_0
# 83 "data/maps/BlackthornCity/scripts.pory"
	closemessage
# 84 "data/maps/BlackthornCity/scripts.pory"
	release
	end


BlackthornCity_Sign_Text_0:
# 6 "data/maps/BlackthornCity/scripts.pory"
	.string "BLACKTHORN CITY -\n"
	.string "A quiet mountain retreat.$"

BlackthornCity_Gym_Sign_Text_0:
# 15 "data/maps/BlackthornCity/scripts.pory"
	.string "BLACKTHORN CITY POKéMON GYM\n"
	.string "LEADER: CLAIR\p"
	.string "The blessed user of DRAGON-\n"
	.string "TYPE POKéMON!$"

BlackthornCity_Ice_Path_Ahead_Sign_Text_0:
# 24 "data/maps/BlackthornCity/scripts.pory"
	.string "ICE PATH is up ahead!\n"
	.string "Beware of slippery, icy ground.$"

BlackthornCity_Move_Specialists_House_Sign_Text_0:
# 33 "data/maps/BlackthornCity/scripts.pory"
	.string "BLACKTHORN CITY -\n"
	.string "POKéMON MOVE SPECIALISTS' HOUSE$"

BlackthornCity_TrainerTips_Sign_Text_0:
# 42 "data/maps/BlackthornCity/scripts.pory"
	.string "TRAINER TIPS!\n"
	.string "SHINY POKéMON are extremely rare.\p"
	.string "These POKéMON can differ from\n"
	.string "standard encounters.$"

BlackthornCity_Battle_Girl_Text_0:
# 52 "data/maps/BlackthornCity/scripts.pory"
	.string "Keep following this path uphill\n"
	.string "and you'll see the GYM.\p"
	.string "It's pretty intimidating!$"

BlackthornCity_Old_Man_Text_0:
# 62 "data/maps/BlackthornCity/scripts.pory"
	.string "This used to be a quiet,\n"
	.string "yet mysterious, small village...$"

BlackthornCity_Old_Woman_Text_0:
# 72 "data/maps/BlackthornCity/scripts.pory"
	.string "An old folk story tells\n"
	.string "of a POKéMON in JOHTO...\p"
	.string "They say it helped pave\n"
	.string "way for this city.$"

BlackthornCity_Man_Text_0:
# 82 "data/maps/BlackthornCity/scripts.pory"
	.string "LORELEI visits us sometimes,\n"
	.string "although, strictly business.\p"
	.string "She's from the ELITE FOUR,\n"
	.string "just like CLAIR'S cousin.$"
