GoldenrodCity_MapScripts::
	.byte 0


GoldenrodCity_Sign::
# 5 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 6 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Sign_Text_0
# 7 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 8 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_GameCorner_Sign::
# 14 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 15 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_GameCorner_Sign_Text_0
# 16 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 17 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MiniGameTentVoltorbFlip_Sign::
# 23 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 24 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MiniGameTentVoltorbFlip_Sign_Text_0
# 25 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 26 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MiniGameFortuneTelling_Sign::
# 32 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 33 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MiniGameFortuneTelling_Sign_Text_0
# 34 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 35 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Gym_Sign::
# 41 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 42 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Gym_Sign_Text_0
# 43 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 44 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_DeptStore_Sign::
# 50 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 51 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_DeptStore_Sign_Text_0
# 52 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 53 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MiracleCycleShop_Sign::
# 59 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 60 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MiracleCycleShop_Sign_Text_0
# 61 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 62 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Condominiums_Sign::
# 68 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 69 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Condominiums_Sign_Text_0
# 70 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 71 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_FiveStarHotel_Sign::
# 77 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 78 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_FiveStarHotel_Sign_Text_0
# 79 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 80 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_FlowerShop_Sign::
# 86 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 87 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_FlowerShop_Sign_Text_0
# 88 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 89 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Underground_Sign::
# 95 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 96 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Underground_Sign_Text_0
# 97 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 98 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MagnetTrainStation_Sign::
# 104 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 105 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MagnetTrainStation_Sign_Text_0
# 106 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 107 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_RadioTower_Sign::
# 113 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 114 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_RadioTower_Sign_Text_0
# 115 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 116 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Woman_1::
# 122 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 123 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 124 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Woman_1_Text_0
# 125 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 126 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Woman_2::
# 132 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 133 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 134 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Woman_2_Text_0
# 135 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 136 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Lass::
# 142 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 143 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 144 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Lass_Text_0
# 145 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Lass_Text_1
# 146 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 147 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Beauty::
# 153 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 154 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 155 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Beauty_Text_0
# 156 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 157 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Balding_Man::
# 163 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 164 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 165 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Balding_Man_Text_0
# 166 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 167 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Boy::
# 173 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 174 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 175 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Boy_Text_0
# 176 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 177 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_GuardTom::
# 183 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 184 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 185 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_GuardTom_Text_0
# 186 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 187 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_GuardJerry::
# 193 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 194 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 195 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_GuardJerry_Text_0
# 196 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 197 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_LittleGirl::
# 203 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 204 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 205 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_LittleGirl_Text_0
# 206 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 207 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Sign_Text_0:
# 6 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "A happening, big city!$"

GoldenrodCity_GameCorner_Sign_Text_0:
# 15 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "JOHTO GAME CORNER$"

GoldenrodCity_MiniGameTentVoltorbFlip_Sign_Text_0:
# 24 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD VOLTORB FLIP -\n"
	.string "MINI-GAME CORNER$"

GoldenrodCity_MiniGameFortuneTelling_Sign_Text_0:
# 33 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD FORTUNE TELLING -\n"
	.string "MINI-GAME CORNER$"

GoldenrodCity_Gym_Sign_Text_0:
# 42 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY POKéMON GYM -\n"
	.string "LEADER: NORMAN\p"
	.string "A man in pursuit of power!$"

GoldenrodCity_DeptStore_Sign_Text_0:
# 51 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD DEPT. STORE -\n"
	.string "Full selection of goods, all here!$"

GoldenrodCity_MiracleCycleShop_Sign_Text_0:
# 60 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "MIRACLE CYCLE SHOP\p"
	.string "You won't believe it's not even a\n"
	.string "miracle... It's a new BICYCLE!$"

GoldenrodCity_Condominiums_Sign_Text_0:
# 69 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY HEIGHTS -\n"
	.string "Affordable JOHTO CONDOMINIUMS!$"

GoldenrodCity_FiveStarHotel_Sign_Text_0:
# 78 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY HEIGHTS -\n"
	.string "JOHTO'S FIVE-STAR GOLDENROD HOTEL!$"

GoldenrodCity_FlowerShop_Sign_Text_0:
# 87 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "FLOWER SHOP\p"
	.string "A small shop, providing lots\n"
	.string "of natural beauty!$"

GoldenrodCity_Underground_Sign_Text_0:
# 96 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "UNDERGROUND TUNNEL ENTRANCE\p"
	.string "Watch out! Stay off of your\n"
	.string "bike in the tunnel.$"

GoldenrodCity_MagnetTrainStation_Sign_Text_0:
# 105 "data/maps/GoldenrodCity/scripts.pory"
	.string "JOHTO-KANTO MAGNET TRAIN LINE\n"
	.string "GOLDENROD CITY STATION$"

GoldenrodCity_RadioTower_Sign_Text_0:
# 114 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "RADIO TOWER\p"
	.string "A network providing the WORLD\n"
	.string "with useful, interesting information!$"

GoldenrodCity_Woman_1_Text_0:
# 124 "data/maps/GoldenrodCity/scripts.pory"
	.string "Hi! Um...\n"
	.string "Are you okay?\p"
	.string "You look worried... TEAM ROCKET?\n"
	.string "No, they aren't here...\p"
	.string "The JOHTO GAME CORNER is run\n"
	.string "by GOLDENROD CITY'S people!$"

GoldenrodCity_Woman_2_Text_0:
# 134 "data/maps/GoldenrodCity/scripts.pory"
	.string "It might be a silly name\n"
	.string "for it, but...\p"
	.string "You definitely need a SQUIRT BOTTLE\n"
	.string "to pass by those weird trees.$"

GoldenrodCity_Lass_Text_0:
# 144 "data/maps/GoldenrodCity/scripts.pory"
	.string "Huh, you're from KANTO?\n"
	.string "I've been there, actually...\p"
	.string "To be honest, it's just a\n"
	.string "bit disappointing...$"

GoldenrodCity_Lass_Text_1:
# 145 "data/maps/GoldenrodCity/scripts.pory"
	.string "For starters, you know, everything\n"
	.string "in KANTO is basic and overpriced.\p"
	.string "There's a BICYCLE SHOP here too,\n"
	.string "so, take a good look around!$"

GoldenrodCity_Beauty_Text_0:
# 155 "data/maps/GoldenrodCity/scripts.pory"
	.string "If you haven't seen GOLDENROD'S\n"
	.string "DEPT. STORE, it's a must!\p"
	.string "Especially for TRAINERS!\n"
	.string "They have almost everything!$"

GoldenrodCity_Balding_Man_Text_0:
# 165 "data/maps/GoldenrodCity/scripts.pory"
	.string "MIRACLE CYCLE does wonders with\n"
	.string "any kind of BICYCLE!\p"
	.string "I left my broken BICYCLE with\n"
	.string "them for a day...\p"
	.string "Came back, and... Wow!\n"
	.string "Good as new! No charge at all!$"

GoldenrodCity_Boy_Text_0:
# 175 "data/maps/GoldenrodCity/scripts.pory"
	.string "A mini-device that can play my\n"
	.string "favorite RADIO CHANNEL anywhere...\p"
	.string "Honestly, that would be sweet.\n"
	.string "I think SILPH CO.'S on it!$"

GoldenrodCity_GuardTom_Text_0:
# 185 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY... It's generally\n"
	.string "pretty safe...\p"
	.string "I don't question it, though.\n"
	.string "The pay here's slightly better.$"

GoldenrodCity_GuardJerry_Text_0:
# 195 "data/maps/GoldenrodCity/scripts.pory"
	.string "My associate is honestly the\n"
	.string "only threat to my peace...\p"
	.string "I need more time off...$"

GoldenrodCity_LittleGirl_Text_0:
# 205 "data/maps/GoldenrodCity/scripts.pory"
	.string "Oh, you know BILL?!\n"
	.string "That's awesome!\p"
	.string "He needs to come visit us\n"
	.string "again soon! I miss him!$"
