GoldenrodCity_MapScripts::
	.byte 0


GoldenrodCity_GameCorner_Sign::
# 5 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 6 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_GameCorner_Sign_Text_0
# 7 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 8 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MiniGameTentVoltorbFlip_Sign::
# 14 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 15 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MiniGameTentVoltorbFlip_Sign_Text_0
# 16 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 17 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_MiniGameFortuneTelling_Sign::
# 23 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 24 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_MiniGameFortuneTelling_Sign_Text_0
# 25 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 26 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Woman_1::
# 32 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 33 "data/maps/GoldenrodCity/scripts.pory"
	faceplayer
# 34 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Woman_1_Text_0
# 35 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 36 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_Gym_Sign::
# 42 "data/maps/GoldenrodCity/scripts.pory"
	lock
# 43 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Gym_Sign_Text_0
# 44 "data/maps/GoldenrodCity/scripts.pory"
	closemessage
# 45 "data/maps/GoldenrodCity/scripts.pory"
	release
	end


GoldenrodCity_GameCorner_Sign_Text_0:
# 6 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY -\n"
	.string "JOHTO GAME CORNER$"

GoldenrodCity_MiniGameTentVoltorbFlip_Sign_Text_0:
# 15 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD VOLTORB FLIP -\n"
	.string "MINI-GAME CORNER$"

GoldenrodCity_MiniGameFortuneTelling_Sign_Text_0:
# 24 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD FORTUNE TELLING -\n"
	.string "MINI-GAME CORNER$"

GoldenrodCity_Woman_1_Text_0:
# 34 "data/maps/GoldenrodCity/scripts.pory"
	.string "Hi! Um...\n"
	.string "Are you okay?\p"
	.string "You look worried... TEAM ROCKET?\n"
	.string "No, they aren't here...\p"
	.string "The JOHTO GAME CORNER is run\n"
	.string "by GOLDENROD CITY'S people!$"

GoldenrodCity_Gym_Sign_Text_0:
# 43 "data/maps/GoldenrodCity/scripts.pory"
	.string "GOLDENROD CITY POKéMON GYM -\n"
	.string "LEADER: NORMAN\p"
	.string "A man in pursuit of power!$"
