EcruteakCity_MapScripts::
	.byte 0


EcruteakCity_Sign::
# 5 "data/maps/EcruteakCity/scripts.pory"
	lock
# 6 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Sign_Text_0
# 7 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 8 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Gym_Sign::
# 14 "data/maps/EcruteakCity/scripts.pory"
	lock
# 15 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Gym_Sign_Text_0
# 16 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 17 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_BurnedTower_Sign::
# 23 "data/maps/EcruteakCity/scripts.pory"
	lock
# 24 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_BurnedTower_Sign_Text_0
# 25 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 26 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_BarrierStation_Sign::
# 32 "data/maps/EcruteakCity/scripts.pory"
	lock
# 33 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_BarrierStation_Sign_Text_0
# 34 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 35 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_KimonoDanceTheater_Sign::
# 41 "data/maps/EcruteakCity/scripts.pory"
	lock
# 42 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_KimonoDanceTheater_Sign_Text_0
# 43 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 44 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Old_Man_1::
# 50 "data/maps/EcruteakCity/scripts.pory"
	lock
# 51 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 52 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Old_Man_1_Text_0
# 53 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 54 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Old_Woman::
# 60 "data/maps/EcruteakCity/scripts.pory"
	lock
# 61 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 62 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Old_Woman_Text_0
# 63 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 64 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Hiker::
# 70 "data/maps/EcruteakCity/scripts.pory"
	lock
# 71 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 72 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Hiker_Text_0
# 73 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 74 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Lass::
# 80 "data/maps/EcruteakCity/scripts.pory"
	lock
# 81 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 82 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Lass_Text_0
# 83 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 84 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Man::
# 90 "data/maps/EcruteakCity/scripts.pory"
	lock
# 91 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 92 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Man_Text_0
# 93 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 94 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Battle_Girl::
# 100 "data/maps/EcruteakCity/scripts.pory"
	lock
# 101 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 102 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Battle_Girl_Text_0
# 103 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 104 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Gym_Roadblock_Old_Man::
# 110 "data/maps/EcruteakCity/scripts.pory"
	lock
# 111 "data/maps/EcruteakCity/scripts.pory"
	faceplayer
# 112 "data/maps/EcruteakCity/scripts.pory"
	msgbox EcruteakCity_Gym_Roadblock_Old_Man_Text_0
# 113 "data/maps/EcruteakCity/scripts.pory"
	closemessage
# 114 "data/maps/EcruteakCity/scripts.pory"
	release
	end


EcruteakCity_Sign_Text_0:
# 6 "data/maps/EcruteakCity/scripts.pory"
	.string "ECRUTEAK CITY -\n"
	.string "A historical, mythical city.$"

EcruteakCity_Gym_Sign_Text_0:
# 15 "data/maps/EcruteakCity/scripts.pory"
	.string "ECRUTEAK CITY POKéMON GYM -\n"
	.string "LEADER: MORTY\p"
	.string "The mystic seer of the future!$"

EcruteakCity_BurnedTower_Sign_Text_0:
# 24 "data/maps/EcruteakCity/scripts.pory"
	.string "ECRUTEAK CITY -\n"
	.string "BURNED TOWER\p"
	.string "It was destroyed by some mysterious\n"
	.string "flames, it's unsafe... Do not enter.$"

EcruteakCity_BarrierStation_Sign_Text_0:
# 33 "data/maps/EcruteakCity/scripts.pory"
	.string "ECRUTEAK CITY -\n"
	.string "BELLCHIME TRAIL\p"
	.string "No tresspassing by the\n"
	.string "unworthy...\p"
	.string "BELL TOWER ahead!$"

EcruteakCity_KimonoDanceTheater_Sign_Text_0:
# 42 "data/maps/EcruteakCity/scripts.pory"
	.string "ECRUTEAK CITY -\n"
	.string "KIMONO DANCE THEATER HALL\p"
	.string "Witness the elegant choreography\n"
	.string "of JOHTO'S culture and traditions!$"

EcruteakCity_Old_Man_1_Text_0:
# 52 "data/maps/EcruteakCity/scripts.pory"
	.string "You're welcome to stroll here\n"
	.string "on BELLCHIME TRAIL, but...\p"
	.string "Only those worthy may pass\n"
	.string "into BELL TOWER ahead.$"

EcruteakCity_Old_Woman_Text_0:
# 62 "data/maps/EcruteakCity/scripts.pory"
	.string "Lovely weather isn't it? Yes,\n"
	.string "I would say! Ohoho...$"

EcruteakCity_Hiker_Text_0:
# 72 "data/maps/EcruteakCity/scripts.pory"
	.string "Don't go in BURNED TOWER!\n"
	.string "There's some sort of curse...\p"
	.string "The magical fire could spread\n"
	.string "out of nowhere, and...\p"
	.string "Oh...\n"
	.string "Uh, sorry, kid!$"

EcruteakCity_Lass_Text_0:
# 82 "data/maps/EcruteakCity/scripts.pory"
	.string "KIMONO GIRLS are so fancy...\n"
	.string "I wish I could imitate them.$"

EcruteakCity_Man_Text_0:
# 92 "data/maps/EcruteakCity/scripts.pory"
	.string "MORTY is a seer, but not much\n"
	.string "of a FORTUNE-TELLER, honestly.\p"
	.string "Prophecies aren't exactly clear...\n"
	.string "They don't always make sense.$"

EcruteakCity_Battle_Girl_Text_0:
# 102 "data/maps/EcruteakCity/scripts.pory"
	.string "The KIMONO GIRLS are tough!\n"
	.string "But if you can beat them...\p"
	.string "Maybe you'd be able to visit\n"
	.string "BELL TOWER...$"

EcruteakCity_Gym_Roadblock_Old_Man_Text_0:
# 112 "data/maps/EcruteakCity/scripts.pory"
	.string "Ever since LUGIA'S home burned down,\n"
	.string "MORTY hasn't been able to find it...\p"
	.string "I'm sorry, he is away, for now...\n"
	.string "You may want to return later.$"
