TopsoilTown_House2_MapScripts::
	.byte 0


TopsoilTown_House2_Man::
# 5 "data/maps/TopsoilTown_House2/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown_House2/scripts.pory"
	faceplayer
# 7 "data/maps/TopsoilTown_House2/scripts.pory"
	msgbox TopsoilTown_House2_Man_Text_0
# 8 "data/maps/TopsoilTown_House2/scripts.pory"
	closemessage
# 9 "data/maps/TopsoilTown_House2/scripts.pory"
	release
	end


TopsoilTown_House2_Man_Text_0:
# 7 "data/maps/TopsoilTown_House2/scripts.pory"
	.string "You're dressed up very, very\n"
	.string "weirdly... Do you not get hot?$"
