LindenTown_House3_MapScripts::
	.byte 0


LindenTown_House3_Rocker::
# 5 "data/maps/LindenTown_House3/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House3/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House3/scripts.pory"
	msgbox LindenTown_House3_Rocker_Text_0
# 8 "data/maps/LindenTown_House3/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House3/scripts.pory"
	release
	end


LindenTown_House3_Rocker_Text_0:
# 7 "data/maps/LindenTown_House3/scripts.pory"
	.string "Three brave explorers ventured into\n"
	.string "the KAIETEUR JUNGLE, years ago.\p"
	.string "As legend has it, DR. FUJI was\n"
	.string "among the three.$"
