LindenTown_House9_MapScripts::
	.byte 0


LindenTown_House9_Fat_Man::
# 5 "data/maps/LindenTown_House9/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House9/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House9/scripts.pory"
	msgbox LindenTown_House9_Fat_Man_Text_0
# 8 "data/maps/LindenTown_House9/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House9/scripts.pory"
	release
	end


LindenTown_House9_Fat_Man_Text_0:
# 7 "data/maps/LindenTown_House9/scripts.pory"
	.string "Science rules...\n"
	.string "It's totally worth the hype.$"
