TopsoilTown_House3_MapScripts::
	.byte 0


TopsoilTown_House3_Battle_Girl::
# 5 "data/maps/TopsoilTown_House3/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown_House3/scripts.pory"
	faceplayer
# 7 "data/maps/TopsoilTown_House3/scripts.pory"
	msgbox TopsoilTown_House3_Battle_Girl_Text_0
# 8 "data/maps/TopsoilTown_House3/scripts.pory"
	closemessage
# 9 "data/maps/TopsoilTown_House3/scripts.pory"
	release
	end


TopsoilTown_House3_Battle_Girl_Text_0:
# 7 "data/maps/TopsoilTown_House3/scripts.pory"
	.string "Hi, stranger!\n"
	.string "Only farmers live here!\p"
	.string "Wild POKéMON? ...Nope!\n"
	.string "Anytime they wander in, shoo!$"
