CanalaveCity_Gym_2F_MapScripts::
	.byte 0


CanalaveCity_Gym_2F_BlackBelt_David_Battle::
# 5 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	trainerbattle_single TRAINER_BLACK_BELT_DAVID, CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_0, CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_1
# 6 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	msgbox CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_2
# 7 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	release
	end


CanalaveCity_Gym_2F_Hiker_Gary_Battle::
# 13 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_GARY, CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_0, CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_1
# 14 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	msgbox CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_2
# 15 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	release
	end


CanalaveCity_Gym_2F_Lass_Porchia_Battle::
# 21 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	trainerbattle_single TRAINER_LASS_PORCHIA, CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_0, CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_1
# 22 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	msgbox CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_2
# 23 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	release
	end


CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_0:
# 5 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Hyah!\n"
	.string "Hah, what?!\p"
	.string "Can't you see I'm training?$"

CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_1:
# 5 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "You interruped my training!\n"
	.string "Now all my POKéMON fainted!$"

CanalaveCity_Gym_2F_BlackBelt_David_Battle_Text_2:
# 6 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Gah!\n"
	.string "The audacity of this KANTONIAN!$"

CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_0:
# 13 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Heh, I know your dirty secret!\n"
	.string "You love to battle!\p"
	.string "...With POKéMON, of course!$"

CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_1:
# 13 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Yep, I knew you liked battling!$"

CanalaveCity_Gym_2F_Hiker_Gary_Battle_Text_2:
# 14 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "I know you like to battle.\n"
	.string "Be sure to say thank you!$"

CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_0:
# 21 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Um, did you just touch me?\n"
	.string "...\p"
	.string "Just kidding! I touched you! Haha,\n"
	.string "you're it!$"

CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_1:
# 21 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Argh! Why did my plan fail?$"

CanalaveCity_Gym_2F_Lass_Porchia_Battle_Text_2:
# 22 "data/maps/CanalaveCity_Gym_2F/scripts.pory"
	.string "Please leave me alone!$"
