# 1 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"

# 2 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
Cherrygrove_PokemonCenter_B1F_MapScripts::
# 3 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
# 4 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
# 5 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
# 6 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
# 7 "data/maps/Cherrygrove_PokemonCenter_B1F/scripts.pory"
	.byte 0
