LindenTown_House5_MapScripts::
	.byte 0


LindenTown_House5_Old_Woman::
# 5 "data/maps/LindenTown_House5/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House5/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House5/scripts.pory"
	msgbox LindenTown_House5_Old_Woman_Text_0
# 8 "data/maps/LindenTown_House5/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House5/scripts.pory"
	release
	end


LindenTown_House5_Old_Woman_Text_0:
# 7 "data/maps/LindenTown_House5/scripts.pory"
	.string "Have you heard of the\n"
	.string "SEVII ISLANDS?\p"
	.string "Each island was formed daily,\n"
	.string "up until the seventh day.\p"
	.string "It reminds me of an old\n"
	.string "saying, tied to our world...$"
