LindenTown_House4_MapScripts::
	.byte 0


LindenTown_House4_Little_Girl::
# 5 "data/maps/LindenTown_House4/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House4/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House4/scripts.pory"
	msgbox LindenTown_House4_Little_Girl_Text_0
# 8 "data/maps/LindenTown_House4/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House4/scripts.pory"
	release
	end


LindenTown_House4_Little_Girl_Text_0:
# 7 "data/maps/LindenTown_House4/scripts.pory"
	.string "Hi! My parents aren't\n"
	.string "home right now...\p"
	.string "I can't talk to strangers!\n"
	.string "Stranger danger! Let's play later!$"
