Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "Oh, is that a TOWN MAP?\p"
    .string "That gives me an idea...\n"
    .string "I'll make it up to you, with this!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received the\n"
    .string "WORLD MAP from the girl.$"

Route16_House_Text_ExplainHM02::
    .string "It's a wonderfully convenient\n"
    .string "upgrade to the TOWN MAP!\p"
    .string "Please, put it to good use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"

