KaieteurJungle_Route10_MapScripts::
	.byte 0


KaieteurJungle_Route10_Sign::
# 5 "data/maps/KaieteurJungle_Route10/scripts.pory"
	lock
# 6 "data/maps/KaieteurJungle_Route10/scripts.pory"
	msgbox KaieteurJungle_Route10_Sign_Text_0
# 7 "data/maps/KaieteurJungle_Route10/scripts.pory"
	closemessage
# 8 "data/maps/KaieteurJungle_Route10/scripts.pory"
	release
	end


KaieteurJungle_Route10_Sign_Text_0:
# 6 "data/maps/KaieteurJungle_Route10/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 10$"
