OlivineCity_MapScripts::
	.byte 0


OlivineCity_Gym_Roadblock_Battle_Girl::
# 5 "data/maps/OlivineCity/scripts.pory"
	lock
# 6 "data/maps/OlivineCity/scripts.pory"
	faceplayer
# 7 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Gym_Roadblock_Battle_Girl_Text_0
# 8 "data/maps/OlivineCity/scripts.pory"
	closemessage
# 9 "data/maps/OlivineCity/scripts.pory"
	release
	end


OlivineCity_Gym_Roadblock_Battle_Girl_Text_0:
# 7 "data/maps/OlivineCity/scripts.pory"
	.string "I will only let you pass if you are\n"
	.string "a master fighter.\p"
	.string "To do that, you need to beat\n"
	.string "CHUCK in Cianwood City Gym.$"
