TopsoilTown_House4_MapScripts::
	.byte 0


TopsoilTown_House4_Boy::
# 5 "data/maps/TopsoilTown_House4/scripts.pory"
	lock
# 6 "data/maps/TopsoilTown_House4/scripts.pory"
	faceplayer
# 7 "data/maps/TopsoilTown_House4/scripts.pory"
	msgbox TopsoilTown_House4_Boy_Text_0
# 8 "data/maps/TopsoilTown_House4/scripts.pory"
	closemessage
# 9 "data/maps/TopsoilTown_House4/scripts.pory"
	release
	end


TopsoilTown_House4_Boy_Text_0:
# 7 "data/maps/TopsoilTown_House4/scripts.pory"
	.string "What's with the get-up?\n"
	.string "Are you from the future?\p"
	.string "POKé BALL? No, we don't use\n"
	.string "them much, here...$"
