LindenTown_House7_MapScripts::
	.byte 0


LindenTown_House7_Picnicker::
# 5 "data/maps/LindenTown_House7/scripts.pory"
	lock
# 6 "data/maps/LindenTown_House7/scripts.pory"
	faceplayer
# 7 "data/maps/LindenTown_House7/scripts.pory"
	msgbox LindenTown_House7_Picnicker_Text_0
# 8 "data/maps/LindenTown_House7/scripts.pory"
	closemessage
# 9 "data/maps/LindenTown_House7/scripts.pory"
	release
	end


LindenTown_House7_Picnicker_Text_0:
# 7 "data/maps/LindenTown_House7/scripts.pory"
	.string "Um... Hello.\n"
	.string "Do I know you? No...\p"
	.string "I don't know why I left\n"
	.string "my door unlocked, honestly.$"
