GoldenrodCity_GTS_Outside_MapScripts::
	.byte 0


GoldenrodCity_GTS_Outside_Sign::
# 5 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 6 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Sign_Text_0
# 7 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 8 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Fat_Man::
# 14 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 15 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	faceplayer
# 16 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Fat_Man_Text_0
# 17 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 18 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Battle_Girl::
# 24 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 25 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	faceplayer
# 26 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Battle_Girl_Text_0
# 27 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 28 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Man::
# 34 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 35 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	faceplayer
# 36 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Man_Text_0
# 37 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 38 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Worker_F::
# 44 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 45 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	faceplayer
# 46 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Worker_F_Text_0
# 47 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 48 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Gentleman::
# 54 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	lock
# 55 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	faceplayer
# 56 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	msgbox GoldenrodCity_GTS_Outside_Gentleman_Text_0
# 57 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	closemessage
# 58 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	release
	end


GoldenrodCity_GTS_Outside_Sign_Text_0:
# 6 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "GLOBAL TERMINAL TOWER -\n"
	.string "GOLDENROD CITY\p"
	.string "An amazing, and completely\n"
	.string "GLOBAL, TERMINAL!$"

GoldenrodCity_GTS_Outside_Fat_Man_Text_0:
# 16 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "I wandered into some upper\n"
	.string "floors of the tower...\p"
	.string "Man! There are some really,\n"
	.string "really tough TRAINERS there!\p"
	.string "I'll stick with trading...$"

GoldenrodCity_GTS_Outside_Battle_Girl_Text_0:
# 26 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "Have you ever been to the\n"
	.string "BATTLE RESORT near ROUTE 40?\p"
	.string "The battling style there's... unique.$"

GoldenrodCity_GTS_Outside_Man_Text_0:
# 36 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "What's hip and happenin'?\n"
	.string "Say, you're from KANTO?\p"
	.string "Aren't you glad the WORLD'S\n"
	.string "more vast than it seems?$"

GoldenrodCity_GTS_Outside_Worker_F_Text_0:
# 46 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "I won't disclose my current\n"
	.string "financial situation, but...\p"
	.string "Knowing GOLDENROD is the shining\n"
	.string "CITY of commerce...\p"
	.string "Well, things are good!$"

GoldenrodCity_GTS_Outside_Gentleman_Text_0:
# 56 "data/maps/GoldenrodCity_GTS_Outside/scripts.pory"
	.string "I wonder what became of the\n"
	.string "GLOBAL POLICE aboard S.S. ANNE...$"
