KaieteurJungle_Route7_MapScripts::
	.byte 0


KaieteurJungle_Route7_FujiMemo_Sign::
# 8 "data/maps/KaieteurJungle_Route7/scripts.pory"
	lock
# 9 "data/maps/KaieteurJungle_Route7/scripts.pory"
	msgbox KaieteurJungle_Route7_FujiMemo_Sign_Text_0
# 10 "data/maps/KaieteurJungle_Route7/scripts.pory"
	msgbox KaieteurJungle_Route7_FujiMemo_Sign_Text_1
# 11 "data/maps/KaieteurJungle_Route7/scripts.pory"
	msgbox KaieteurJungle_Route7_FujiMemo_Sign_Text_2
# 12 "data/maps/KaieteurJungle_Route7/scripts.pory"
	msgbox KaieteurJungle_Route7_FujiMemo_Sign_Text_3
# 13 "data/maps/KaieteurJungle_Route7/scripts.pory"
	closemessage
# 14 "data/maps/KaieteurJungle_Route7/scripts.pory"
	release
	end


KaieteurJungle_Route7_Sign::
# 20 "data/maps/KaieteurJungle_Route7/scripts.pory"
	lock
# 21 "data/maps/KaieteurJungle_Route7/scripts.pory"
	msgbox KaieteurJungle_Route7_Sign_Text_0
# 22 "data/maps/KaieteurJungle_Route7/scripts.pory"
	closemessage
# 23 "data/maps/KaieteurJungle_Route7/scripts.pory"
	release
	end


KaieteurJungle_Route7_FujiMemo_Sign_Text_0:
# 9 "data/maps/KaieteurJungle_Route7/scripts.pory"
	.string "It's a notice from DR. FUJI,\n"
	.string "dated: JULY 5, 1996.\p"
	.string "Following our success, advancements\n"
	.string "in research are quite impressive.$"

KaieteurJungle_Route7_FujiMemo_Sign_Text_1:
# 10 "data/maps/KaieteurJungle_Route7/scripts.pory"
	.string "It has been a year since the\n"
	.string "discovery of MEW in GUYANA.\p"
	.string "We are flooded with support\n"
	.string "from a respectable, private investor.$"

KaieteurJungle_Route7_FujiMemo_Sign_Text_2:
# 11 "data/maps/KaieteurJungle_Route7/scripts.pory"
	.string "Our science fellow, DR. BLAINE,\n"
	.string "has also proved to be of help.\p"
	.string "We brought MEWTWO into GUYANA\n"
	.string "to meet their parent.$"

KaieteurJungle_Route7_FujiMemo_Sign_Text_3:
# 12 "data/maps/KaieteurJungle_Route7/scripts.pory"
	.string "MEWTWO and MEW seem to get\n"
	.string "along very well, lovingly, even!\p"
	.string "We are truly touched, deep in\n"
	.string "our hearts, filled with hope.$"

KaieteurJungle_Route7_Sign_Text_0:
# 21 "data/maps/KaieteurJungle_Route7/scripts.pory"
	.string "KAIETEUR JUNGLE -\n"
	.string "ROUTE 7$"
